### PR TITLE
Add about, policies, admin sections

### PR DESCRIPTION
**Pull request by ateucher**
Hi @jules32,

Here is a draft of the "about" section, the policies (access and storage), and access instructions (GH team based and shared-password).

I think the structure of separating the policies from procedures works quite well, as does separating the instructions for shared-password vs github-based access. The latter is still a bit muddy in places due to slightly different setups (at least right now) for NASA and NMFS, but I think it's pretty close, and we can tighten up as we iron out the implementation of the NMFS hub(s).

I have a few `TODOs` peppered about as comments to follow up on as we figure things out. 

I also haven't integrated the usage report as much as we should; I will continue to work on it!

### CODE REVIEW

**Comment by jules32** [comment]
Reviewing now! I've built locally and will add a few commits locally that I will push, alongside the GitHub.com reviewer process

**Comment by jules32** [comment]
Hi @ateucher, 

I think this is looking really good. The organization is good and how you've generalized for NASA and NOAA. 

Let's talk tomorrow - I think we are nearly there with the categories, but I think the "workshop" language is still leaves some confusion. 

- my drawing below is how I've been thinking about this, does this make sense and match your understanding of access? 
  - note the starter decision tree questions would need more work!
  -  this is opposed to having "longterm access" and "workshop/event/champions/shared-password" be the first split, which is a very logical way to categorize but I think the access paths are then messier the way we have set them up?
- And if the drawing makes sense, I wonder if "Access Instructions" menu should have "GitHub-based access" and "Password-based access",  rather than "workshops" 
- I pushed some commits to this branch along this thinking, and we can discuss more when we meet tomorrow.
PXL_20240911_002527800

**Review by ateucher — COMMENTED** [review]
Thanks for this @jules32, those are good changes. And yes, I like that framing better. So we ask the question in `access-policies` and direct them to the relevant page (Github based access vs password based access). And have a blurb at top of each indicating their uses?

**Review by ateucher — COMMENTED** [review]
In the decision tree I also think we need a question about whether or not they will be teaching GitHub in the workshop. So access >= 3 months and/or teaching GitHub, vs 1-week access after the workshop and not teaching GitHub...?

**Comment by jules32** [comment]
Yes on both points, I think that sounds good!

**Comment by ateucher** [comment]
I think this addresses all the major points we discussed @jules32. Merging now!

**Pull request merged**
